name: mortality-ami-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - numpy>=1.26
  - pandas>=2.2
  - scikit-learn>=1.3
  - xgboost>=2.0
  - lightgbm>=4.0
  - imbalanced-learn>=0.12
  - optuna>=3.5
  - matplotlib>=3.8
  - seaborn>=0.13
  - plotly>=5.20
  - nbformat>=5.9
  - shap>=0.44
  - streamlit>=1.36
  - joblib>=1.3
  - mlflow>=2.13
  - reportlab>=4.0
  # - kaleido
  - openpyxl
  - xlrd
  - scipy
  - statsmodels
  - pytorch>=2.3
  - torchvision>=0.18
  - pytorch-lightning>=2.4
  - captum>=0.7
  - scikit-plot>=0.3.7
  - pip:
      - python-decouple>=3.8
      - pyyaml>=6.0.1
      - jinja2>=3.1.4
      - pytest>=8.2
      - pytest-cov>=5.0
      - kaleido
